# lappy
# function
# rvest
#


# lapply ------------------------------------------------------------------

my_list <- 1:10

my_list^2

my_numbers <- NULL
for (i in 1:10) {
  my_numbers <- c(my_numbers, i^2)
}

lapply(1:10, function(x){ #can be a new or pre-set function
  return(x^2) ##always use return!
}) #[[1]] means the first one in the list

x <- NULL

my_square <- function(x){
  return(x^2)
}


lapply(my_list, my_square) ## this is a pre-set funciton, don't write "()" behind the function name!

x <- NULL
my_letter <- function(a){
  return(paste0("#",toupper(a),"#"))
}
q <- my_letter(letters)
class(q)  --# this is a character

t <- lapply(letters, my_letter) # returns list
class(t) --# this is a list

unlist( # use unlist to get vectors(rather than list generated by lapply)
lapply(letters, function(a){
  return(paste0("#",toupper(a),"#"))
}))

v <- sapply(letters, my_letter) #returns vectors

as.character(v)


# rvest -------------------------------------------------------------------

library(rvest) #Easily Harvest (Scrape) Web Pages

t <- read_html('https://insidebigdata.com/?s=big+data')
write_html(t, 't.html')

t %>% 
  html_nodes()


# practice_scraping -------------------------------------------------------

m <- read_html("https://www.wired.com/search/?q=big%20data&page=1&sort=score")
write_html(m, "m.html")

titles <- 
m %>% 
  html_nodes('.archive-item-component__title') %>% 
  html_text()

time <-
m %>% 
  html_nodes("time") %>% 
  html_text()

my_link <- 
unique(m %>% 
  html_nodes('.archive-item-component__link') %>% 
  html_attr('href')) #href means Hypertext REFerence

summary <-
m %>% 
  html_nodes(".archive-item-component__desc") %>% 
  html_text()

df <- data.frame('title' = titles, "time" = time, 'links' = my_link, 'summary' = summary)
## if you don't change the row content, the dataframe will not be created.